export const Books = [
  {
    title: "Harry Potter and Prisoner",
    img: "http://i2.wp.com/geekdad.com/wp-content/uploads/2013/02/HP1-Kibuishi.jpg",
    author: "Philosopher’s Stone",
    price: "$ 10.00",
  },
  {
    title: "Harry Potter and Prisoner",
    img: "http://i2.wp.com/geekdad.com/wp-content/uploads/2013/02/HP1-Kibuishi.jpg",
    author: "Philosopher’s Stone",
    price: "$ 10.00",
  },
  {
    title: "Harry Potter and Prisoner",
    img: "http://i2.wp.com/geekdad.com/wp-content/uploads/2013/02/HP1-Kibuishi.jpg",
    author: "Philosopher’s Stone",
    price: "$ 10.00",
  },
  {
    title: "Harry Potter and Prisoner",
    img: "http://i2.wp.com/geekdad.com/wp-content/uploads/2013/02/HP1-Kibuishi.jpg",
    author: "Philosopher’s Stone",
    price: "$ 10.00",
  },
  {
    title: "Harry Potter and Prisoner",
    img: "http://i2.wp.com/geekdad.com/wp-content/uploads/2013/02/HP1-Kibuishi.jpg",
    author: "Philosopher’s Stone",
    price: "$ 10.00",
  },
  {
    title: "Harry Potter and Prisoner",
    img: "http://i2.wp.com/geekdad.com/wp-content/uploads/2013/02/HP1-Kibuishi.jpg",
    author: "Philosopher’s Stone",
    price: "$ 10.00",
  },
  {
    title: "Harry Potter and Prisoner",
    img: "http://i2.wp.com/geekdad.com/wp-content/uploads/2013/02/HP1-Kibuishi.jpg",
    author: "Philosopher’s Stone",
    price: "$ 10.00",
  },
  {
    title: "Harry Potter and Prisoner",
    img: "http://i2.wp.com/geekdad.com/wp-content/uploads/2013/02/HP1-Kibuishi.jpg",
    author: "Philosopher’s Stone",
    price: "$ 10.00",
  },
  {
    title: "Harry Potter and Prisoner",
    img: "http://i2.wp.com/geekdad.com/wp-content/uploads/2013/02/HP1-Kibuishi.jpg",
    author: "Philosopher’s Stone",
    price: "$ 10.00",
  },
  {
    title: "Harry Potter and Prisoner",
    img: "http://i2.wp.com/geekdad.com/wp-content/uploads/2013/02/HP1-Kibuishi.jpg",
    author: "Philosopher’s Stone",
    price: "$ 10.00",
  },
  {
    title: "Harry Potter and Prisoner",
    img: "http://i2.wp.com/geekdad.com/wp-content/uploads/2013/02/HP1-Kibuishi.jpg",
    author: "Philosopher’s Stone",
    price: "$ 10.00",
  },
  {
    title: "Harry Potter and Prisoner",
    img: "http://i2.wp.com/geekdad.com/wp-content/uploads/2013/02/HP1-Kibuishi.jpg",
    author: "Philosopher’s Stone",
    price: "$ 10.00",
  },
  {
    title: "Harry Potter and Prisoner",
    img: "http://i2.wp.com/geekdad.com/wp-content/uploads/2013/02/HP1-Kibuishi.jpg",
    author: "Philosopher’s Stone",
    price: "$ 10.00",
  },
];
